package com.example.repository

import com.example.BuildConfig
import com.example.database.ChatDao
import com.example.model.*
import com.example.network.RetrofitClient
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.withContext

class ChatRepository(private val chatDao: ChatDao) {
    val allSessions: Flow<List<ChatSession>> = chatDao.getAllSessions()

    fun getMessages(sessionId: Int): Flow<List<ChatMessage>> = chatDao.getMessagesForSession(sessionId)

    suspend fun createSession(title: String): Int {
        return chatDao.insertSession(ChatSession(title = title)).toInt()
    }

    suspend fun saveMessage(sessionId: Int, role: String, text: String) {
        chatDao.insertMessage(ChatMessage(sessionId = sessionId, role = role, text = text))
    }

    suspend fun editMessageAndWipeAfter(sessionId: Int, messageId: Int, newText: String) {
        chatDao.updateMessageText(messageId, newText)
        chatDao.deleteMessagesAfter(sessionId, messageId)
    }
    
    suspend fun deleteSession(sessionId: Int) {
        chatDao.deleteMessagesForSession(sessionId)
        chatDao.deleteSessionById(sessionId)
    }

    fun getTotalSessions(): Flow<Int> = chatDao.getTotalSessions()
    
    fun getTotalMessages(): Flow<Int> = chatDao.getTotalMessages()
    
    suspend fun wipeAllData() {
        chatDao.deleteAllMessages()
        chatDao.deleteAllSessions()
    }

    suspend fun generateAiResponse(history: List<ChatMessage>, systemInstruction: String): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            throw Exception("Please configure your Gemini API key in the Secrets panel.")
        }
        
        val contents = history.map { 
            Content(role = it.role, parts = listOf(Part(text = it.text)))
        }
        
        val request = GenerateContentRequest(
            contents = contents,
            systemInstruction = Content(parts = listOf(Part(text = systemInstruction)))
        )
        
        val response = RetrofitClient.service.generateContent(apiKey, request)
        response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text ?: throw Exception("No response from AI.")
    }

    suspend fun generateImage(prompt: String, style: String, aspectRatio: String): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            throw Exception("Please configure your Gemini API key in the Secrets panel.")
        }
        
        val fullPrompt = if (style.isNotEmpty() && style != "None") {
            "$prompt in $style style"
        } else {
            prompt
        }
        
        val request = GenerateContentRequest(
            contents = listOf(Content(parts = listOf(Part(text = fullPrompt)))),
            generationConfig = GenerationConfig(
                imageConfig = ImageConfig(aspectRatio = aspectRatio, imageSize = "1K"),
                responseModalities = listOf("TEXT", "IMAGE")
            )
        )
        
        val response = RetrofitClient.service.generateContentWithModel(
            model = "gemini-3.1-flash-image-preview",
            apiKey = apiKey,
            request = request
        )
        
        val inlineData = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull { it.inlineData != null }?.inlineData
        val base64Data = inlineData?.data ?: throw Exception("No image generated by AI.")
        
        // Save to Database
        try {
            chatDao.insertGeneratedImage(
                GeneratedImage(
                    prompt = prompt,
                    style = style,
                    aspectRatio = aspectRatio,
                    imageBase64 = base64Data
                )
            )
        } catch (e: Exception) {
            // Non-blocking log/ignore if db insertion fails
        }
        
        base64Data
    }

    suspend fun updateSessionFavorite(sessionId: Int, isFavorite: Boolean) {
        chatDao.updateSessionFavorite(sessionId, isFavorite)
    }

    fun getAllGeneratedImages(): Flow<List<GeneratedImage>> = chatDao.getAllGeneratedImages()

    suspend fun deleteGeneratedImage(id: Int) {
        chatDao.deleteGeneratedImageById(id)
    }

    suspend fun clearAllImages() {
        chatDao.deleteAllGeneratedImages()
    }
    
    fun generateAiResponseStream(history: List<ChatMessage>, systemInstruction: String): Flow<String> = kotlinx.coroutines.flow.flow {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            throw Exception("Please configure your Gemini API key in the Secrets panel.")
        }
        
        val contents = history.map { 
            Content(role = it.role, parts = listOf(Part(text = it.text)))
        }
        
        val request = GenerateContentRequest(
            contents = contents,
            systemInstruction = Content(parts = listOf(Part(text = systemInstruction)))
        )
        
        val response = RetrofitClient.service.generateContentStream(apiKey, request)
        val adapter = RetrofitClient.moshi.adapter(GenerateContentResponse::class.java)
        
        response.byteStream().bufferedReader().use { reader ->
            var line: String?
            while (reader.readLine().also { line = it } != null) {
                val currentLine = line!!
                if (currentLine.startsWith("data: ")) {
                    val jsonStr = currentLine.substring(6)
                    if (jsonStr.trim() == "[DONE]") break
                    try {
                        val chunkResponse = adapter.fromJson(jsonStr)
                        val textChunk = chunkResponse?.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                        if (textChunk != null) {
                            emit(textChunk)
                        }
                    } catch (e: Exception) {
                        // Ignore parsing errors for individual chunks
                    }
                }
            }
        }
    }.flowOn(Dispatchers.IO)
}
